spring:
  application:
    name: FlowDemo
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/default_db}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_URL:localhost}
      password: ${REDIS_PASSWORD:}
      port: ${REDIS_ PORT:}
      database: 0 # 默认数据库索引
