spring:
  application:
    name: FlowDemo
  datasource:
    url: {DB_URL:jdbc:mysql://localhost:3306/default_db}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
